data_source: "/home/claudia/synthetic_uncertainty/data/v1-0-beta" 
target_location: "/home/claudia/synthetic_uncertainty/data/v1-0-beta_NOISY" 
overwrite_exitsting: True 
make_single_masks: False
make_noisefree_testset: False
file_extension: "png"

create_new_train_val_set: False
val_split:
  make_val_split: False
  val_frac: 0.1
  val_frac_seed: 123

semantic: 
  make_noisy_labels: False
  noise_levels: [20, 40, 60, 80, 100]
  noise_params:
    global_flip_prob: 0.1
    class_flip_dict: 
      # 1: (0.1, [2])
      # 3: (0.3, [2,4])

instance_3class: 
  make_noisy_labels: False
  noise_levels: [30, 50, 70] #[20, 40, 60, 80, 100]
  border_width: 2           


FG_BG: 
  make_noisy_labels: True
  noise_levels: [20, 40, 60, 80, 100]
  noise_params:
    max_pixel_val: 1.
    prob_shift: 0.1 
    max_shift_strength: 10 
    prob_scale: 0.1
    max_scale_strength: 7 
    prob_elastic: 0.1 
    min_alpha_elastic: 5
    max_alpha_elastic: 10 
    min_sigma_elastic: 0.5
    max_sigma_elastic: 2 
    prob_leave_out: 0.05


variations: 
  process_noisefree: False
  make_noisy_labels: False
  

sanity_check:
  execute: False
  samples: 5 




